include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: true
    lines_longer_than_80_chars: false
    avoid_redundant_argument_values: false
    prefer_if_elements_to_conditional_expressions: false