name: services_list
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  firebase_database: ^9.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.1.0
  flutter_svg: ^1.0.3
  get: ^4.6.1
  intl: ^0.17.0
  mask_text_input_formatter: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true